version: '3.7'
services:
  mongo_container:
    network_mode: host
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes: 
      - ./home/mongodb:/home/mongodb
      - ./data/db
    command: mongod